services:
  api:
    build:
      context: .
    container_name: imei_check_api
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      API_AUTH_TOKEN: ${API_AUTH_TOKEN}
      IMEICHECK_API_TOKEN: ${IMEICHECK_API_TOKEN}
      IMEICHECK_API_URL: ${IMEICHECK_API_URL}
      ALLOWED_USER_IDS: ${ALLOWED_USER_IDS}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["poetry", "run", "uvicorn", "app.app.api:app", "--host", "0.0.0.0", "--port", "8000"]

  bot:
    build:
      context: .
    container_name: imei_check_bot
    restart: always
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      API_AUTH_TOKEN: ${API_AUTH_TOKEN}
      IMEICHECK_API_TOKEN: ${IMEICHECK_API_TOKEN}
      IMEICHECK_API_URL: ${IMEICHECK_API_URL}
      ALLOWED_USER_IDS: ${ALLOWED_USER_IDS}
    depends_on:
      - api
    volumes:
      - .:/app
    command: ["poetry", "run", "python", "app/app/main.py"]
